#!/bin/env ruby
# encoding: utf-8
# frozen_string_literal: true

require 'bundler/setup'
require 'fileutils'
require 'uglifier'

def combine(list_of_files, output_file = 'out.txt')
  File.open(output_file, 'w') { |f| f.puts(list_of_files.map { |s| IO.read(s) }) }
  system "sed -i '' '/sourceMappingURL/d' ./#{output_file}"
end

def minify_js(source, output)
  File.open(output, 'w') { |file| file.write(Uglifier.compile(File.read(source))) }
end

namespace :test do
  task :html do
    system 'open example/*.html'
  end

  task all: :html
end

namespace :sass do
  #####
  # This task will create the necessary directories should they not already exiest.  It initilizes with cleanup.
  #####
  task create_dirs: :cleanup do
    FileUtils.mkdir_p('dist/css') unless Dir.exist? 'dist/css'
  end

  #####
  # This task will move fonts, images, and javascript files from assets to their respective dist directory locations.
  #####
  task :create_js_files do
    combine(['assets/javascripts/fontstrap/storage.js',
             'assets/javascripts/fontstrap/fontstrap-utilities.js',
             'assets/javascripts/fontstrap/alignBlocks.jquery.js',
             'assets/javascripts/fontstrap/fullScreenBackground.jquery.js',
             'assets/javascripts/fontstrap/offcanvasMenu.jquery.js',
             'assets/javascripts/fontstrap/keepOnScreen.jquery.js'], 'dist/js/fontstrap-features.js')
    minify_js('dist/js/fontstrap-features.js', 'dist/js/fontstrap-features.min.js')
    minify_js('dist/js/fontstrap.js', 'dist/js/fontstrap.min.js')
    combine(['assets/javascripts/bootstrap/popper.min.js', 'assets/javascripts/bootstrap/bootstrap.min.js'], 'dist/js/popper-bootstrap.min.js')
  end

  #####
  # This task combines create_dirs and move_static_content.
  #####
  task setup: %i[create_dirs create_js_files]

  #####
  # This task removes the dist directory.
  #####
  task :cleanup do
    FileUtils.remove_dir 'dist/css' if Dir.exist? 'dist/css'
  end

  #####
  # This task combines cleanup, setup, and compile.
  #####
  task reset: %i[cleanup compile]

  #####
  # This task will create the minified version of the fontstrap css.  It initilizes with setup.
  #####
  task compile: :setup do
    system 'sass assets/stylesheets/_full.scss dist/css/fontstrap.min.css --style compressed'
    system 'sass assets/stylesheets/_full_square.scss dist/css/fontstrap-square.min.css --style compressed'
  end

  #####
  # This task will create the non minified version of the fontstrap css.  It initilizes with setup.
  #####
  task compile_full: :setup do
    system 'sass assets/stylesheets/_full.scss dist/css/fontstrap.css'
    system 'sass assets/stylesheets/_full_square.scss dist/css/fontstrap-square.css'
  end

  #####
  # This task will create the minified version of fontrap css and then continue to watch for more changes.  It initilizes with setup.  You will need to use `ctrl + c` to stop.
  #####
  task watch: :setup do
    system 'sass --watch assets/stylesheets/_full.scss:dist/css/fontstrap.min.css --style compressed'
  end

  #####
  # This task will create the minified version of square fontrap css and then continue to watch for more changes.  It initilizes with setup.  You will need to use `ctrl + c` to stop.
  #####
  task watch_square: :setup do
    system 'sass --watch assets/stylesheets/_full_square.scss:dist/css/fontstrap-square.min.css --style compressed'
  end
end
